services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'savitar'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Savitar@123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Savitar@123'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  kafka:
    image: apache/kafka:3.7.1
    ports:
      - '9092:9092'

# Names our volume
volumes:
  my-db: