// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/Savitar465/task-manager/app/controller"
	"github.com/Savitar465/task-manager/app/repository"
	"github.com/Savitar465/task-manager/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitApp() *Initialization {
	gormDB := InitDB()
	issueRepositoryImpl := repository.IssueRepositoryInit(gormDB)
	issueServiceImpl := service.IssueServiceInit(issueRepositoryImpl)
	issueControllerImpl := controller.IssueControllerrInit(issueServiceImpl)
	initialization := NewInitialization(issueRepositoryImpl, issueServiceImpl, issueControllerImpl)
	return initialization
}

// injector.go:

var dbsql = InitDB

var db = wire.NewSet(dbsql)
